const cards = [
  ['Action (set A)', 'Action (set B)', 'Animal (set A)', 'Animal (set B)', 'Clothes', 'Emotions', 'Clothes', 'Animal (set B)'],
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: 'src/images/cry.jpg',
      audioSrc: 'src/sounds/cry.mp3',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: 'src/images/dance.jpg',
      audioSrc: 'src/sounds/dance.mp3',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: 'src/images/dive.jpg',
      audioSrc: 'src/sounds/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: 'src/images/draw.jpg',
      audioSrc: 'src/sounds/draw.mp3',
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'src/images/fish.jpg',
      audioSrc: 'src/sounds/fish.mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: 'src/images/fly.jpg',
      audioSrc: 'src/sounds/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: 'src/images/hug.jpg',
      audioSrc: 'src/sounds/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: 'src/images/jump.jpg',
      audioSrc: 'src/sounds/jump.mp3',
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      image: 'src/images/open.jpg',
      audioSrc: 'src/sounds/open.mp3',
    },
    {
      word: 'play',
      translation: 'играть',
      image: 'src/images/play.jpg',
      audioSrc: 'src/sounds/play.mp3',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: 'src/images/point.jpg',
      audioSrc: 'src/sounds/point.mp3',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: 'src/images/ride.jpg',
      audioSrc: 'src/sounds/ride.mp3',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: 'src/images/run.jpg',
      audioSrc: 'src/sounds/run.mp3',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: 'src/images/sing.jpg',
      audioSrc: 'src/sounds/sing.mp3',
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: 'src/images/skip.jpg',
      audioSrc: 'src/sounds/skip.mp3',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: 'src/images/swim.jpg',
      audioSrc: 'src/sounds/swim.mp3',
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: 'src/images/cat.jpg',
      audioSrc: 'src/sounds/cat.mp3',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: 'src/images/chick.jpg',
      audioSrc: 'src/sounds/chick.mp3',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'src/images/chicken.jpg',
      audioSrc: 'src/sounds/chicken.mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'src/images/dog.jpg',
      audioSrc: 'src/sounds/dog.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: 'src/images/horse.jpg',
      audioSrc: 'src/sounds/horse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'src/images/pig.jpg',
      audioSrc: 'src/sounds/pig.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: 'src/images/rabbit.jpg',
      audioSrc: 'src/sounds/rabbit.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: 'src/images/sheep.jpg',
      audioSrc: 'src/sounds/sheep.mp3',
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: 'src/images/bird.jpg',
      audioSrc: 'src/sounds/bird.mp3',
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: 'src/images/fish1.jpg',
      audioSrc: 'src/sounds/fish.mp3',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: 'src/images/frog.jpg',
      audioSrc: 'src/sounds/frog.mp3',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: 'src/images/giraffe.jpg',
      audioSrc: 'src/sounds/giraffe.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'src/images/lion.jpg',
      audioSrc: 'src/sounds/lion.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'src/images/mouse.jpg',
      audioSrc: 'src/sounds/mouse.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'src/images/turtle.jpg',
      audioSrc: 'src/sounds/turtle.mp3',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'src/images/dolphin.jpg',
      audioSrc: 'src/sounds/dolphin.mp3',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'src/images/skirt.jpg',
      audioSrc: 'src/sounds/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'src/images/pants.jpg',
      audioSrc: 'src/sounds/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'src/images/blouse.jpg',
      audioSrc: 'src/sounds/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'src/images/dress.jpg',
      audioSrc: 'src/sounds/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'src/images/boot.jpg',
      audioSrc: 'src/sounds/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'src/images/shirt.jpg',
      audioSrc: 'src/sounds/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'src/images/coat.jpg',
      audioSrc: 'src/sounds/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: 'src/images/shoe.jpg',
      audioSrc: 'src/sounds/shoe.mp3',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: 'src/images/sad.jpg',
      audioSrc: 'src/sounds/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'src/images/angry.jpg',
      audioSrc: 'src/sounds/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'src/images/happy.jpg',
      audioSrc: 'src/sounds/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: 'src/images/tired.jpg',
      audioSrc: 'src/sounds/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'src/images/surprised.jpg',
      audioSrc: 'src/sounds/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: 'src/images/scared.jpg',
      audioSrc: 'src/sounds/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: 'src/images/smile.jpg',
      audioSrc: 'src/sounds/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: 'src/images/laugh.jpg',
      audioSrc: 'src/sounds/laugh.mp3',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'src/images/skirt.jpg',
      audioSrc: 'src/sounds/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'src/images/pants.jpg',
      audioSrc: 'src/sounds/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'src/images/blouse.jpg',
      audioSrc: 'src/sounds/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'src/images/dress.jpg',
      audioSrc: 'src/sounds/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'src/images/boot.jpg',
      audioSrc: 'src/sounds/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'src/images/shirt.jpg',
      audioSrc: 'src/sounds/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'src/images/coat.jpg',
      audioSrc: 'src/sounds/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: 'src/images/shoe.jpg',
      audioSrc: 'src/sounds/shoe.mp3',
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: 'src/images/bird.jpg',
      audioSrc: 'src/sounds/bird.mp3',
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: 'src/images/fish1.jpg',
      audioSrc: 'src/sounds/fish.mp3',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: 'src/images/frog.jpg',
      audioSrc: 'src/sounds/frog.mp3',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: 'src/images/giraffe.jpg',
      audioSrc: 'src/sounds/giraffe.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'src/images/lion.jpg',
      audioSrc: 'src/sounds/lion.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'src/images/mouse.jpg',
      audioSrc: 'src/sounds/mouse.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'src/images/turtle.jpg',
      audioSrc: 'src/sounds/turtle.mp3',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'src/images/dolphin.jpg',
      audioSrc: 'src/sounds/dolphin.mp3',
    },
  ],
];

export default cards;
