const cards = [
  ['Action (set A)', 'Action (set B)', 'Animal (set A)', 'Animal (set B)', 'Clothes', 'Emotions', 'Transport', 'School'],
  [
    {
      id: 1,
      word: 'cry',
      translation: 'плакать',
      image: './src/cards/images/cry.jpg',
      audioSrc: './src/cards/sounds/cry.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 2,
      word: 'dance',
      translation: 'танцевать',
      image: './src/cards/images/dance.jpg',
      audioSrc: './src/cards/sounds/dance.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 3,
      word: 'dive',
      translation: 'нырять',
      image: './src/cards/images/dive.jpg',
      audioSrc: './src/cards/sounds/dive.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 4,
      word: 'draw',
      translation: 'рисовать',
      image: './src/cards/images/draw.jpg',
      audioSrc: './src/cards/sounds/draw.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 5,
      word: 'fish',
      translation: 'ловить рыбу',
      image: './src/cards/images/fish.jpg',
      audioSrc: './src/cards/sounds/fish.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 6,
      word: 'fly',
      translation: 'летать',
      image: './src/cards/images/fly.jpg',
      audioSrc: './src/cards/sounds/fly.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 7,
      word: 'hug',
      translation: 'обнимать',
      image: './src/cards/images/hug.jpg',
      audioSrc: './src/cards/sounds/hug.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 8,
      word: 'jump',
      translation: 'прыгать',
      image: './src/cards/images/jump.jpg',
      audioSrc: './src/cards/sounds/jump.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
  ],
  [
    {
      id: 9,
      word: 'open',
      translation: 'открывать',
      image: './src/cards/images/open.jpg',
      audioSrc: './src/cards/sounds/open.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 10,
      word: 'play',
      translation: 'играть',
      image: './src/cards/images/play.jpg',
      audioSrc: './src/cards/sounds/play.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 11,
      word: 'point',
      translation: 'указывать',
      image: './src/cards/images/point.jpg',
      audioSrc: './src/cards/sounds/point.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 12,
      word: 'ride',
      translation: 'ездить',
      image: './src/cards/images/ride.jpg',
      audioSrc: './src/cards/sounds/ride.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 13,
      word: 'run',
      translation: 'бегать',
      image: './src/cards/images/run.jpg',
      audioSrc: './src/cards/sounds/run.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 14,
      word: 'sing',
      translation: 'петь',
      image: './src/cards/images/sing.jpg',
      audioSrc: './src/cards/sounds/sing.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 15,
      word: 'skip',
      translation: 'пропускать',
      image: './src/cards/images/skip.jpg',
      audioSrc: './src/cards/sounds/skip.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 16,
      word: 'swim',
      translation: 'плавать',
      image: './src/cards/images/swim.jpg',
      audioSrc: './src/cards/sounds/swim.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
  ],
  [
    {
      id: 17,
      word: 'cat',
      translation: 'кот',
      image: './src/cards/images/cat.jpg',
      audioSrc: './src/cards/sounds/cat.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 18,
      word: 'chick',
      translation: 'цыплёнок',
      image: './src/cards/images/chick.jpg',
      audioSrc: './src/cards/sounds/chick.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 19,
      word: 'chicken',
      translation: 'курица',
      image: './src/cards/images/chicken.jpg',
      audioSrc: './src/cards/sounds/chicken.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 20,
      word: 'dog',
      translation: 'собака',
      image: './src/cards/images/dog.jpg',
      audioSrc: './src/cards/sounds/dog.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 21,
      word: 'horse',
      translation: 'лошадь',
      image: './src/cards/images/horse.jpg',
      audioSrc: './src/cards/sounds/horse.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 22,
      word: 'pig',
      translation: 'свинья',
      image: './src/cards/images/pig.jpg',
      audioSrc: './src/cards/sounds/pig.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 23,
      word: 'rabbit',
      translation: 'кролик',
      image: './src/cards/images/rabbit.jpg',
      audioSrc: './src/cards/sounds/rabbit.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 24,
      word: 'sheep',
      translation: 'овца',
      image: './src/cards/images/sheep.jpg',
      audioSrc: './src/cards/sounds/sheep.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
  ],
  [
    {
      id: 25,
      word: 'bird',
      translation: 'птица',
      image: './src/cards/images/bird.jpg',
      audioSrc: './src/cards/sounds/bird.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 26,
      word: 'fish',
      translation: 'рыба',
      image: './src/cards/images/fish1.jpg',
      audioSrc: './src/cards/sounds/fish.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 27,
      word: 'frog',
      translation: 'жаба',
      image: './src/cards/images/frog.jpg',
      audioSrc: './src/cards/sounds/frog.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 28,
      word: 'giraffe',
      translation: 'жираф',
      image: './src/cards/images/giraffe.jpg',
      audioSrc: './src/cards/sounds/giraffe.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 29,
      word: 'lion',
      translation: 'лев',
      image: './src/cards/images/lion.jpg',
      audioSrc: './src/cards/sounds/lion.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 30,
      word: 'mouse',
      translation: 'мышь',
      image: './src/cards/images/mouse.jpg',
      audioSrc: './src/cards/sounds/mouse.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 31,
      word: 'turtle',
      translation: 'черепаха',
      image: './src/cards/images/turtle.jpg',
      audioSrc: './src/cards/sounds/turtle.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 32,
      word: 'dolphin',
      translation: 'дельфин',
      image: './src/cards/images/dolphin.jpg',
      audioSrc: './src/cards/sounds/dolphin.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
  ],
  [
    {
      id: 33,
      word: 'skirt',
      translation: 'юбка',
      image: './src/cards/images/skirt.jpg',
      audioSrc: './src/cards/sounds/skirt.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 34,
      word: 'pants',
      translation: 'брюки',
      image: './src/cards/images/pants.jpg',
      audioSrc: './src/cards/sounds/pants.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 35,
      word: 'blouse',
      translation: 'блузка',
      image: './src/cards/images/blouse.jpg',
      audioSrc: './src/cards/sounds/blouse.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 36,
      word: 'dress',
      translation: 'платье',
      image: './src/cards/images/dress.jpg',
      audioSrc: './src/cards/sounds/dress.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 37,
      word: 'boot',
      translation: 'ботинок',
      image: './src/cards/images/boot.jpg',
      audioSrc: './src/cards/sounds/boot.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 38,
      word: 'shirt',
      translation: 'рубашка',
      image: './src/cards/images/shirt.jpg',
      audioSrc: './src/cards/sounds/shirt.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 39,
      word: 'coat',
      translation: 'пальто',
      image: './src/cards/images/coat.jpg',
      audioSrc: './src/cards/sounds/coat.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 40,
      word: 'shoe',
      translation: 'туфли',
      image: './src/cards/images/shoe.jpg',
      audioSrc: './src/cards/sounds/shoe.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
  ],
  [
    {
      id: 41,
      word: 'sad',
      translation: 'грустный',
      image: './src/cards/images/sad.jpg',
      audioSrc: './src/cards/sounds/sad.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 42,
      word: 'angry',
      translation: 'сердитый',
      image: './src/cards/images/angry.jpg',
      audioSrc: './src/cards/sounds/angry.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 43,
      word: 'happy',
      translation: 'счастливый',
      image: './src/cards/images/happy.jpg',
      audioSrc: './src/cards/sounds/happy.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 44,
      word: 'tired',
      translation: 'уставший',
      image: './src/cards/images/tired.jpg',
      audioSrc: './src/cards/sounds/tired.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 45,
      word: 'surprised',
      translation: 'удивлённый',
      image: './src/cards/images/surprised.jpg',
      audioSrc: './src/cards/sounds/surprised.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 46,
      word: 'scared',
      translation: 'испуганный',
      image: './src/cards/images/scared.jpg',
      audioSrc: './src/cards/sounds/scared.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 47,
      word: 'smile',
      translation: 'улыбка',
      image: './src/cards/images/smile.jpg',
      audioSrc: './src/cards/sounds/smile.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 48,
      word: 'laugh',
      translation: 'смех',
      image: './src/cards/images/laugh.jpg',
      audioSrc: './src/cards/sounds/laugh.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
  ],
  [
    {
      id: 49,
      word: 'taxi',
      translation: 'такси',
      image: './src/cards/images/taxi.jpg',
      audioSrc: './src/cards/sounds/taxi.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 50,
      word: 'ship',
      translation: 'корабль',
      image: './src/cards/images/ship.jpg',
      audioSrc: './src/cards/sounds/ship.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 51,
      word: 'rocket',
      translation: 'ракета',
      image: './src/cards/images/rocket.jpg',
      audioSrc: './src/cards/sounds/rocket.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 52,
      word: 'raft',
      translation: 'плот',
      image: './src/cards/images/raft.jpg',
      audioSrc: './src/cards/sounds/raft.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 53,
      word: 'car',
      translation: 'машина',
      image: './src/cards/images/car.jpg',
      audioSrc: './src/cards/sounds/car.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 54,
      word: 'bus',
      translation: 'автобус',
      image: './src/cards/images/bus.jpg',
      audioSrc: './src/cards/sounds/bus.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 55,
      word: 'boat',
      translation: 'лодка',
      image: './src/cards/images/boat.jpg',
      audioSrc: './src/cards/sounds/boat.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 56,
      word: 'bike',
      translation: 'велосипед',
      image: './src/cards/images/bike.jpg',
      audioSrc: './src/cards/sounds/bike.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
  ],
  [
    {
      id: 57,
      word: 'school',
      translation: 'школа',
      image: './src/cards/images/school.jpg',
      audioSrc: './src/cards/sounds/school.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 58,
      word: 'bag',
      translation: 'рюкзак',
      image: './src/cards/images/bag.jpg',
      audioSrc: './src/cards/sounds/bag.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 59,
      word: 'board',
      translation: 'доска',
      image: './src/cards/images/board.jpg',
      audioSrc: './src/cards/sounds/board.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 60,
      word: 'book',
      translation: 'книга',
      image: './src/cards/images/book.jpg',
      audioSrc: './src/cards/sounds/book.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 61,
      word: 'desk',
      translation: 'парта',
      image: './src/cards/images/desk.jpg',
      audioSrc: './src/cards/sounds/desk.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 62,
      word: 'notebook',
      translation: 'тетрадь',
      image: './src/cards/images/notebook.jpg',
      audioSrc: './src/cards/sounds/notebook.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 63,
      word: 'pen',
      translation: 'ручка',
      image: './src/cards/images/pen.jpg',
      audioSrc: './src/cards/sounds/pen.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
    {
      id: 64,
      word: 'pencil',
      translation: 'карандаш',
      image: './src/cards/images/pencil.jpg',
      audioSrc: './src/cards/sounds/pencil.mp3',
      trained: 0,
      correct: 0,
      incorrect: 0,
    },
  ],
];

export default cards;
